services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - todolist-network

  server:
    build: ./backend
    container_name: server
    ports:
      - "9000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/merntodo
    depends_on:
      - mongodb
    networks:
      - todolist-network

  client:
    build: ./frontend
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge
